FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /app
COPY pubspec.* ./
RUN flutter pub get
COPY . .

EXPOSE 4200
CMD ["flutter", "run", "-d", "web-server", "--web-hostname", "0.0.0.0", "--web-port", "4200"]
