# =========================
# CONFIG-SERVER - PROD
# =========================
FROM openjdk:17-slim

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8888

# Profil production
ENV SPRING_PROFILES_ACTIVE=prod

# JVM optimisée prod
# ExitOnOutOfMemoryError : évite un conteneur bloqué
ENV JAVA_OPTS="-XX:MaxRAMPercentage=80 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError"

ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"]