# =========================
# EUREKA-SERVER - STAGING
# =========================
FROM openjdk:17-slim

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8761

# Profil pré-production
ENV SPRING_PROFILES_ACTIVE=staging

# JVM intermédiaire
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75 -XX:+UseG1GC"

ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"]