import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'SpeedLine',
      'welcome': 'Welcome',
      'login': 'Login',
      'log_in': 'Log In',
      'sign_up': 'Sign Up',
      'email': 'Email',
      'email_address': 'Email Address',
      'email_hint': 'you@example.com',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'home': 'Home',
      'orders': 'Orders',
      'profile': 'Profile',
      'search_restaurants': 'Search restaurants...',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'order_placed': 'Order Placed Successfully',
      'track_order': 'Track Order',
      
      // Auth screens
      'sign_in': 'Sign In',
      'first_name': 'First Name',
      'first_name_hint': 'first name',
      'last_name': 'Last Name',
      'last_name_hint': 'last name',
      'phone_number': 'Phone Number',
      'phone_hint': '+216 22 345 678',
      'or_continue_with': 'Or continue with',
      'having_trouble': 'Having trouble? ',
      'contact_support': 'Contact Support',
      
      // Validation messages
      'please_enter_email': 'Please enter your email',
      'invalid_email': 'Invalid email',
      'please_enter_password': 'Please enter your password',
      'password_min_length': 'Password must have at least 8 characters',
      'please_enter_first_name': 'Please enter your first name',
      'please_enter_last_name': 'Please enter your last name',
      'please_enter_valid_email': 'Please enter your valid email',
      'please_enter_phone': 'Please enter your phone number',
      'phone_min_length': 'Phone number must have 8 numbers',
      
      // Forgot Password
      'forgot_password_title': 'Forgot Password?',
      'forgot_password_desc': "Don't worry! It happens. Please enter the email address associated with your account.",
      'send_code': 'Send Code',
      'remember_password': 'Remember your password? ',
      
      // Verify OTP
      'verify_code': 'Verify Code',
      'verify_code_desc': 'Please enter the code we just sent to',
      'didnt_receive_code': "Didn't receive the code? ",
      'resend': 'Resend',
      'please_enter_6_digit_code': 'Please enter the 6-digit code',
      'code_resent_success': 'Code resent successfully',
      'verify_identity': 'Verify Your Identity',
      'otp_sent_to': 'We sent a verification code to',
      'code_expired': 'Code Expired',
      'code_expired_message': 'Your OTP code has expired. Please request a new code.',
      'back': 'Back',
      'resend_code': 'Resend',
      'expires_in': 'Expires in',
      'verify_and_login': 'Verify and Login',
      'enter_6_digit_code': 'Please enter a 6-digit code',
      'invalid_or_expired_code': 'Invalid or expired code',
      'login_success': '✓ Login successful!',
      'resend_login_otp_message': 'To resend the code, please log in again',
      'wait': 'Wait',
      'seconds': 'seconds',
      'sec': 's',
      
      // Snackbar messages
      'login_failed': 'Login failed. Please check your credentials.',
      'otp_verification_failed': 'OTP verification failed. Please try again.',
      'otp_verification_success': 'OTP verified successfully!',
      'password_reset_failed': 'Password reset failed. Please try again.',
      'password_reset_complete': 'Your password has been reset successfully!',
      'email_not_found': 'Email not found. Please check and try again.',
      'invalid_credentials': 'Invalid email or password.',
      'generic_error': 'An error occurred. Please try again.',
      'please_wait': 'Please wait...',
      'otp_sent': 'OTP sent successfully to your email.',
      'stay_connected': 'Stay connected',
      
      // Accueil Screen
      'welcome_speedline': 'Welcome to SpeedLine!',
      'welcome_message': 'You are now logged in to your account.\nThe full home screen is coming soon!',
      'welcome_user': 'Welcome',
      
      // Settings Screen
      'settings': 'Settings',
      'account': 'ACCOUNT',
      'edit_profile': 'Edit Profile',
      'manage_preferences': 'Manage your profile information',
      'change_password': 'Change Password',
      'update_security_credentials': 'Update your security credentials',
      'app_preferences': 'APP PREFERENCES',
      'language': 'Language',
      'choose_app_language': 'Choose your app language',
      'dark_mode': 'Dark Mode',
      'enable_dark_theme': 'Enable dark theme',
      'dark_mode_enabled': 'Dark mode enabled',
      'light_mode_enabled': 'Light mode enabled',
      'notifications': 'NOTIFICATIONS',
      'push_notifications': 'Push Notifications',
      'receive_order_updates': 'Receive order updates and offers',
      'email_notifications': 'Email Notifications',
      'receive_news_offers': 'Receive news and special offers',
      'support': 'SUPPORT',
      'help_center': 'Help Center',
      'faq_support_articles': 'FAQ and support articles',
      'contact_us': 'Contact Us',
      'get_in_touch': 'Get in touch with our team',
      'terms_conditions': 'Terms & Conditions',
      'legal_information': 'Legal information and policies',
      'about': 'ABOUT',
      'app_version': 'App Version',
      'logout': 'Logout',
      'are_you_sure_logout': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'select_language': 'Select Language',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      
      // Enable Location Screen
      'enable_location': 'Enable Location Services',
      'location_permission_title': 'What is your location?',
      'location_permission_desc': 'We need to know your location to show you nearby restaurants and provide accurate delivery estimates.',
      'accurate_delivery': 'provide accurate delivery estimates',
      'allow_location_access': 'Allow Location Access',
      'enter_address_manually': 'Enter Address Manually',
      'skip_for_now': 'Skip for now',
      'location_services_disabled': 'Location services are disabled. Please enable them in settings.',
      'location_permission_denied': 'Location permission denied. Please allow access to continue.',
      'location_permanently_denied': 'Location permissions are permanently denied.',
      'open_settings_for_location': 'Please open app settings to allow location access for SpeedLine.',
      'open_settings': 'Open Settings',
      'location_timeout': 'Location request timed out. Please try again.',
      'location_error': 'Failed to get location. Please try again.',
      'detecting_location': 'Detecting location...',
      'privacy_location_note': 'Your location is encrypted and never shared.',
      'enter_your_address': 'Enter Your Address',
      'search_address': 'Search address',
      'address_search_hint': 'e.g. 58 Hedi Chaker Ave., Sfax',
      'confirm_address': 'Confirm Address',
      'retry_gps': 'Retry GPS Detection',
      'manual_address_entry': 'Manual Address Entry',
      'manual_address_coming_soon': 'Manual address entry screen coming soon!',
      'ok': 'OK',

      // Confirm Location Screen
      'confirm_your_location': 'Confirm Your Location',
      'delivery_address': 'Delivery Address',
      'done': 'Done',
      'edit': 'Edit',
      'enter_address_hint': 'Enter your full address...',
      'detecting_address': 'Detecting address...',
      'no_address_found': 'No address found for this location.',
      'tap_map_to_adjust': 'Tap on the map to adjust the pin position.',
      'confirm_this_location': 'Confirm This Location',
      'current_location_label': 'Current location',
      'missing_address_data': 'Missing address data',
      'default_location': 'Sfax, Tunisia',
      'special_for_you': 'Special for You',
      'stores': 'Stores',
      'free_delivery_first_order': 'Free delivery on your first order',
      'order_and_enjoy': 'Order and enjoy!',
      
      // Edit Profile Screen
      'save_changes': 'Save Changes',
      'profile_updated_success': 'Profile updated successfully!',
      'profile_update_error': 'Failed to update profile. Please try again.',
      'choose_photo_source': 'Choose Photo Source',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'remove_photo': 'Remove Photo',
      'uploading': 'Uploading...',
      
      // Profile Screen
      'my_profile': 'My Profile',
      'delivery_addresses': 'Delivery Addresses',
      'manage_addresses': 'Manage your addresses',
      'add_new_address': 'Add New Address',
      'no_address_saved': 'No address saved yet',
      'work_address': 'Work',
      'other_address': 'Other',
      'address_type_label': 'Address Type',
      'my_location_btn': 'My Location',
      'getting_location': 'Getting location...',
      'custom_label_hint': 'e.g. Parents, Gym...',
      'payment_methods': 'Payment Methods',
      'manage_payment': 'Manage your payment methods',
      'add_payment_method': 'Add Payment Method',
      'order_history': 'Order History',
      'view_all_orders': 'View all your past orders',
      'delivered': 'DELIVERED',
      'reorder': 'Reorder',
      'view_details': 'View Details',
      'manage_all': 'Manage All',
      'manage': 'Manage',
      'view_all': 'View All',
      
      // Search Screen
      'search': 'Search',
      'coming_soon': 'Coming soon...',
      
      // Orders Screen
      'my_orders': 'My Orders',
      
      // Main Navigation
      'explore': 'Explore',
      
      // Reset Password
      'reset_password': 'Reset Password',
      'reset_password_desc': "Please enter your new password. Make sure it's at least 6 characters long.",
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'please_enter_password_field': 'Please enter a password',
      'minimum_6_chars': 'Minimum 6 characters',
      'please_confirm_password': 'Please confirm the password',
      'passwords_dont_match': 'Passwords do not match',
      'password_reset_success': 'Password reset successfully!',
      
      // Change Password
      'change_password_title': 'Change Your Password',
      'change_password_desc': 'To change your password, we\'ll send a verification code to your email address.',
      'continue_to_verify': 'Continue',
      'secure_account': 'Keep your account secure by changing your password regularly.',
      
      // Social login in development
      'google_signin_dev': 'Google Sign In - Under development',
      'facebook_signin_dev': 'Facebook Sign In - Under development',
      'register_success': 'Registration successful! Please log in with your credentials.',
      
      // Home/Onboarding screen
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'terms_prefix': 'By continuing, you agree to our ',
      'terms': 'Terms',
      'privacy_policy': 'Privacy Policy',
      
      // Onboarding pages
      'onboarding_page1_title': 'Deliver with',
      'onboarding_page1_highlight': 'Speed & Precision',
      'onboarding_page1_desc': 'Manage your fleet in real-time. The fastest way to get from A to B starts here.',
      'onboarding_page2_title': 'Track Your',
      'onboarding_page2_highlight': 'Order Live',
      'onboarding_page2_desc': 'Real-time tracking keeps you informed every step of the way. Never miss a delivery.',
      'onboarding_page3_title': 'Fast & Reliable',
      'onboarding_page3_highlight': 'Service',
      'onboarding_page3_desc': 'Experience lightning-fast deliveries with our trusted network of professional couriers.',
      
      // Explore Screen
      'restaurants': 'Restaurants',
      'courses': 'Courses',
      'service_courier': 'Service Courier',
      'select_location': 'Select Location',
      'for_you': 'This is for you',
      'promotions': 'Promotions',
      'magasins_aziza': 'Magasins Aziza',
      'free_delivery_title': 'Free Delivery',
      'order_now': 'Order Now, We Treat You!',
      
      // Explore Screen
      'deliver_to': 'Deliver to',
      'current_location': 'Current Location',
      'welcome_back': 'Welcome Back!',
      'what_would_you_like': 'What would you like to order today?',
      'browse_categories': 'Browse Categories',
      'groceries': 'Groceries',
      'special_offer': 'Special Offer',
      'exclusive_deals': 'Exclusive Deals & Discounts',
      'save_up_to': 'Save up to 50% on selected items',
      'explore_now': 'Explore Now',
      'free_delivery_desc': 'On your first order of \$15 or more',
      'popular_now': 'Popular Now',
      'see_all': 'See All',
      'pizza_margherita': 'Pizza Margherita',
      'pizza_desc': 'Fresh mozzarella, tomato sauce',
      'sushi_combo': 'Sushi Combo',
      'sushi_desc': 'Assorted fresh sushi platter',

      // Address type names (selector + type picker)
      'apartment_address': 'Apartment',
      'address_type_home': 'Home',
      'address_type_work': 'Office',
      'address_type_apartment': 'Apartment',
      'address_type_other': 'Other',
      'home_type_subtitle': 'Your personal address',
      'work_type_subtitle': 'Your workplace',
      'apartment_type_subtitle': 'Residence or building',
      'other_type_subtitle': 'Any other address',
      'choose_address_type': 'Choose your address type',

      // Location / Delivery flow
      'session_expired': 'Session expired. Please log in again.',
      'where_to_deliver': 'Where should we deliver?',
      'choose_on_map': 'Choose on map',
      'move_pin_to_adjust': 'Move the pin to adjust the position',
      'continue_btn': 'Continue',
      'what_type_of_place': 'What kind of place is it?',
      'address_selected_for_delivery': 'selected as delivery address',

      // Addresses Screen
      'my_addresses': 'My Addresses',
      'add': 'Add',
      'load_addresses_error': 'Could not load addresses',
      'retry': 'Retry',
      'no_address_hint': 'Tap "Add" to create\nyour first delivery address.',
      'delete_address': 'Delete Address',
      'delete_address_confirm': 'Are you sure you want to delete this address? This action is irreversible.',
      'delete': 'Delete',
      'default_label': 'Default',

      // Address Details Screen
      'home_screen_title': 'Home Address',
      'work_screen_title': 'Work Address',
      'apartment_screen_title': 'Apartment Address',
      'other_screen_title': 'Other Address',
      'address_gps_section': 'Address (GPS detected)',
      'address_not_available': 'Address not available',
      'residence_name': 'Residence / Building name',
      'residence_hint': 'e.g. Les Jardins Residence',
      'floor_section': 'Floor',
      'floor_hint': 'e.g. 3',
      'apartment_number': 'Apt. Number',
      'apartment_hint': 'e.g. A12',
      'extra_info': 'Additional info (optional)',
      'extra_info_hint': 'Access codes, doorbell, landmark...',
      'address_label_section': 'Address Label',
      'label_already_used_badge': 'Label already used',
      'label_required': 'Label is required for this type.',
      'field_required': 'This field is required.',
      'delete_blocked_title': 'Cannot Delete',
      'delete_blocked_content': 'This is your currently active delivery address. Please choose another delivery address before deleting it.',
      'understood': 'Got it',
      'address_deleted': 'Address deleted.',
      'address_delete_error': 'Could not delete address. Please try again.',
      'changes_saved': 'Changes saved successfully!',
      'address_added': 'Address added to your list!',
      'label_already_used_error': 'This label is already used by another address. Choose a different name below \u2193',
      'account_not_found_error': 'Account not found. Please log in again.',
      'invalid_fields_error': 'Some fields are invalid. Please check the information entered.',
      'invalid_gps_error': 'GPS coordinates are invalid. Go back to the map and select again.',
      'personalized': 'Custom',
      'custom_label_other_hint': "e.g. Grandma's house",

      // Profile Screen
      'use_current_location': 'Use current location',
      'premium_member': 'PREMIUM MEMBER',
      'live_badge': 'LIVE',
    },
    'fr': {
      'app_name': 'SpeedLine',
      'welcome': 'Bienvenue',
      'login': 'Connexion',
      'log_in': 'Connexion',
      'sign_up': "S'inscrire",
      'email': 'Email',
      'email_address': 'Adresse Email',
      'email_hint': 'votre@email.com',
      'password': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié?',
      'dont_have_account': "Vous n'avez pas de compte?",
      'home': 'Accueil',
      'orders': 'Commandes',
      'profile': 'Profil',
      'search_restaurants': 'Rechercher des restaurants...',
      'cart': 'Panier',
      'checkout': 'Commander',
      'order_placed': 'Commande passée avec succès',
      'track_order': 'Suivre la commande',
      
      // Auth screens
      'sign_in': 'Se Connecter',
      'first_name': 'Prénom',
      'first_name_hint': 'prénom',
      'last_name': 'Nom',
      'last_name_hint': 'nom',
      'phone_number': 'Numéro de Téléphone',
      'phone_hint': '+216 22 345 678',
      'or_continue_with': 'Ou continuer avec',
      'having_trouble': 'Besoin d\'aide? ',
      'contact_support': 'Contacter le Support',
      
      // Validation messages
      'please_enter_email': 'Veuillez entrer votre email',
      'invalid_email': 'Email invalide',
      'please_enter_password': 'Veuillez entrer votre mot de passe',
      'password_min_length': 'Le mot de passe doit contenir au moins 8 caractères',
      'please_enter_first_name': 'Veuillez entrer votre prénom',
      'please_enter_last_name': 'Veuillez entrer votre nom',
      'please_enter_valid_email': 'Veuillez entrer votre email valide',
      'please_enter_phone': 'Veuillez entrer votre numéro de téléphone',
      'phone_min_length': 'Le numéro doit contenir 8 chiffres',
      
      // Forgot Password
      'forgot_password_title': 'Mot de passe oublié?',
      'forgot_password_desc': "Pas d'inquiétude! Cela arrive. Veuillez entrer l'adresse email associée à votre compte.",
      'send_code': 'Envoyer le Code',
      'remember_password': 'Vous vous souvenez de votre mot de passe? ',
      
      // Verify OTP
      'verify_code': 'Vérifier le Code',
      'verify_code_desc': 'Veuillez entrer le code que nous venons d\'envoyer à',
      'didnt_receive_code': "Vous n'avez pas reçu le code? ",
      'resend': 'Renvoyer',
      'please_enter_6_digit_code': 'Veuillez entrer le code à 6 chiffres',
      'code_resent_success': 'Code renvoyé avec succès',
      'verify_identity': 'Vérifier votre identité',
      'otp_sent_to': 'Nous avons envoyé un code de vérification à',
      'code_expired': 'Code expiré',
      'code_expired_message': 'Votre code OTP a expiré. Veuillez demander un nouveau code.',
      'back': 'Retour',
      'resend_code': 'Renvoyer',
      'expires_in': 'Expire dans',
      'verify_and_login': 'Vérifier et se connecter',
      'enter_6_digit_code': 'Veuillez entrer un code de 6 chiffres',
      'invalid_or_expired_code': 'Code invalide ou expiré',
      'login_success': '✓ Connexion réussie!',
      'resend_login_otp_message': 'Pour renvoyer le code, veuillez vous reconnecter',
      'wait': 'Attendez',
      'seconds': 'secondes',
      'sec': 's',
      
      // Snackbar messages
      'login_failed': 'Échec de la connexion. Veuillez vérifier vos identifiants.',
      'otp_verification_failed': 'Échec de la vérification OTP. Veuillez réessayer.',
      'otp_verification_success': 'OTP vérifié avec succès!',
      'password_reset_failed': 'Échec de la réinitialisation. Veuillez réessayer.',
      'password_reset_complete': 'Votre mot de passe a été réinitialisé avec succès!',
      'email_not_found': 'Email introuvable. Veuillez vérifier et réessayer.',
      'invalid_credentials': 'Email ou mot de passe invalide.',
      'generic_error': 'Une erreur s\'est produite. Veuillez réessayer.',
      'please_wait': 'Veuillez patienter...',
      'otp_sent': 'OTP envoyé avec succès à votre email.',
      'stay_connected': 'Rester connecté',
      
      // Accueil Screen
      'welcome_speedline': 'Bienvenue sur SpeedLine!',
      'welcome_message': 'Vous êtes maintenant connecté à votre compte.\nL\'écran d\'accueil complet arrive bientôt!',
      'welcome_user': 'Bienvenue',
      
      // Settings Screen
      'settings': 'Paramètres',
      'account': 'COMPTE',
      'edit_profile': 'Modifier le Profil',
      'manage_preferences': 'Gérer vos informations de profil',
      'change_password': 'Changer le Mot de Passe',
      'update_security_credentials': 'Mettre à jour vos identifiants de sécurité',
      'app_preferences': 'PRÉFÉRENCES',
      'language': 'Langue',
      'choose_app_language': 'Choisissez la langue de l\'application',
      'dark_mode': 'Mode Sombre',
      'enable_dark_theme': 'Activer le thème sombre',
      'dark_mode_enabled': 'Mode sombre activé',
      'light_mode_enabled': 'Mode clair activé',
      'notifications': 'NOTIFICATIONS',
      'push_notifications': 'Notifications Push',
      'receive_order_updates': 'Recevoir des mises à jour de commande et des offres',
      'email_notifications': 'Notifications Email',
      'receive_news_offers': 'Recevoir des actualités et des offres spéciales',
      'support': 'SUPPORT',
      'help_center': 'Centre d\'Aide',
      'faq_support_articles': 'FAQ et articles de support',
      'contact_us': 'Contactez-Nous',
      'get_in_touch': 'Entrez en contact avec notre équipe',
      'terms_conditions': 'Conditions Générales',
      'legal_information': 'Informations légales et politiques',
      'about': 'À PROPOS',
      'app_version': 'Version de l\'Application',
      'logout': 'Déconnexion',
      'are_you_sure_logout': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'cancel': 'Annuler',
      'select_language': 'Sélectionner la Langue',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      
      // Enable Location Screen
      'enable_location': 'Activer les Services de Localisation',
      'location_permission_title': 'Quelle est votre position?',
      'location_permission_desc': 'Nous devons connaître votre position pour vous montrer les restaurants à proximité et fournir des estimations de livraison précises.',
      'accurate_delivery': 'fournir des estimations de livraison précises',
      'allow_location_access': 'Autoriser l\'Accès à la Localisation',
      'enter_address_manually': 'Entrer l\'Adresse Manuellement',
      'skip_for_now': 'Passer pour l\'instant',
      'location_services_disabled': 'Les services de localisation sont désactivés. Veuillez les activer dans les paramètres.',
      'location_permission_denied': 'Permission de localisation refusée. Veuillez autoriser l\'accès pour continuer.',
      'location_permanently_denied': 'Les autorisations de localisation sont refusées de façon permanente.',
      'open_settings_for_location': 'Veuillez ouvrir les paramètres de l\'application pour autoriser la localisation.',
      'open_settings': 'Ouvrir les Paramètres',
      'location_timeout': 'La demande de localisation a expiré. Veuillez réessayer.',
      'location_error': 'Échec de l\'obtention de la localisation. Réessayez.',
      'detecting_location': 'Détection en cours...',
      'privacy_location_note': 'Votre position est chiffrée et jamais partagée.',
      'enter_your_address': 'Entrez Votre Adresse',
      'search_address': 'Rechercher une adresse',
      'address_search_hint': 'ex: 58 Ave. Hédi Chaker, Sfax',
      'confirm_address': 'Confirmer l\'Adresse',
      'retry_gps': 'Réessayer la Détection GPS',
      'manual_address_entry': 'Saisie Manuelle de l\'Adresse',
      'manual_address_coming_soon': 'L\'écran de saisie manuelle de l\'adresse arrive bientôt!',
      'ok': 'OK',

      // Confirm Location Screen
      'confirm_your_location': 'Confirmer Votre Position',
      'delivery_address': 'Adresse de Livraison',
      'done': 'Terminé',
      'edit': 'Modifier',
      'enter_address_hint': 'Entrez votre adresse complète...',
      'detecting_address': 'Détection de l\'adresse...',
      'no_address_found': 'Aucune adresse trouvée pour cette position.',
      'tap_map_to_adjust': 'Appuyez sur la carte pour ajuster la position du pin.',
      'confirm_this_location': 'Confirmer Cette Position',
      'current_location_label': 'Emplacement actuel',
      'missing_address_data': 'Données d\'adresse manquantes',
      'default_location': 'Sfax, Tunisie',
      'special_for_you': 'Spécial pour Vous',
      'stores': 'Magasins',
      'free_delivery_first_order': 'Livraison gratuite sur votre première commande',
      'order_and_enjoy': 'Commandez et profitez!',
      
      // Edit Profile Screen
      'save_changes': 'Enregistrer les Modifications',
      'profile_updated_success': 'Profil mis à jour avec succès!',
      'profile_update_error': 'Échec de la mise à jour du profil. Veuillez réessayer.',
      'choose_photo_source': 'Choisir la Source de la Photo',
      'take_photo': 'Prendre une Photo',
      'choose_from_gallery': 'Choisir dans la Galerie',
      'remove_photo': 'Supprimer la Photo',
      'uploading': 'Téléchargement...',
      
      // Profile Screen
      'my_profile': 'Mon Profil',
      'delivery_addresses': 'Adresses de Livraison',
      'manage_addresses': 'Gérer vos adresses',
      'add_new_address': 'Ajouter une Nouvelle Adresse',
      'no_address_saved': 'Aucune adresse enregistrée',
      'work_address': 'Travail',
      'other_address': 'Autre',
      'address_type_label': "Type d'adresse",
      'my_location_btn': 'Ma Position',
      'getting_location': 'Récupération du lieu...',
      'custom_label_hint': 'Ex : Parents, Salle de sport...',
      'payment_methods': 'Moyens de Paiement',
      'manage_payment': 'Gérer vos moyens de paiement',
      'add_payment_method': 'Ajouter un Moyen de Paiement',
      'order_history': 'Historique des Commandes',
      'view_all_orders': 'Voir toutes vos commandes passées',
      'delivered': 'LIVRÉ',
      'reorder': 'Recommander',
      'view_details': 'Voir les Détails',
      'manage_all': 'Tout Gérer',
      'manage': 'Gérer',
      'view_all': 'Tout Voir',
      
      // Search Screen
      'search': 'Rechercher',
      'coming_soon': 'Bientôt disponible...',
      
      // Orders Screen
      'my_orders': 'Mes Commandes',
      
      // Main Navigation
      'explore': 'Explorer',
      
      // Reset Password
      'reset_password': 'Réinitialiser le Mot de Passe',
      'reset_password_desc': 'Veuillez entrer votre nouveau mot de passe. Assurez-vous qu\'il contient au moins 6 caractères.',
      'new_password': 'Nouveau Mot de Passe',
      'confirm_password': 'Confirmer le Mot de Passe',
      'please_enter_password_field': 'Veuillez entrer un mot de passe',
      'minimum_6_chars': 'Minimum 6 caractères',
      'please_confirm_password': 'Veuillez confirmer le mot de passe',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'password_reset_success': 'Mot de passe réinitialisé avec succès!',
      
      // Change Password
      'change_password_title': 'Changer Votre Mot de Passe',
      'change_password_desc': 'Pour changer votre mot de passe, nous enverrons un code de vérification à votre adresse e-mail.',
      'continue_to_verify': 'Continuer',
      'secure_account': 'Gardez votre compte sécurisé en changeant régulièrement votre mot de passe.',
      
      // Social login in development
      'google_signin_dev': 'Google Sign In - En cours de développement',
      'facebook_signin_dev': 'Facebook Sign In - En cours de développement',
      'register_success': 'Inscription réussie! Veuillez vous connecter avec vos identifiants.',
      
      // Home/Onboarding screen
      'skip': 'Passer',
      'next': 'Suivant',
      'get_started': 'Commencer',
      'terms_prefix': 'En continuant, vous acceptez nos ',
      'terms': 'Conditions',
      'privacy_policy': 'Politique de confidentialité',
      
      // Onboarding pages
      'onboarding_page1_title': 'Livraison avec',
      'onboarding_page1_highlight': 'Rapidité & Précision',
      'onboarding_page1_desc': 'Gérez votre flotte en temps réel. Le moyen le plus rapide d\'aller d\'un point A à B commence ici.',
      'onboarding_page2_title': 'Suivez votre',
      'onboarding_page2_highlight': 'Commande en Direct',
      'onboarding_page2_desc': 'Le suivi en temps réel vous tient informé à chaque étape. Ne manquez jamais une livraison.',
      'onboarding_page3_title': 'Service Rapide',
      'onboarding_page3_highlight': 'et Fiable',
      'onboarding_page3_desc': 'Profitez de livraisons ultra-rapides avec notre réseau de coursiers professionnels de confiance.',
      
      // Explore Screen
      'restaurants': 'Restaurants',
      'courses': 'Courses',
      'service_courier': 'Service Courrier',
      'select_location': 'Sélectionner un lieu',
      'for_you': 'Ceci est pour vous',
      'promotions': 'Promotions',
      'magasins_aziza': 'Magasins Aziza',
      'free_delivery_title': 'Livraison gratuite',
      'order_now': 'Commandez, nous régalons!',
      
      // Explore Screen
      'deliver_to': 'Livrer à',
      'current_location': 'Localisation actuelle',
      'welcome_back': 'Bon retour!',
      'what_would_you_like': 'Que souhaitez-vous commander aujourd\'hui?',
      'browse_categories': 'Parcourir les catégories',
      'groceries': 'Épicerie',
      'special_offer': 'Offre spéciale',
      'exclusive_deals': 'Offres exclusives et réductions',
      'save_up_to': 'Économisez jusqu\'à 50% sur les articles sélectionnés',
      'explore_now': 'Explorer maintenant',
      'free_delivery_desc': 'Sur votre première commande de 15\$ ou plus',
      'popular_now': 'Populaire maintenant',
      'see_all': 'Voir tout',
      'pizza_margherita': 'Pizza Margherita',
      'pizza_desc': 'Mozzarella fraîche, sauce tomate',
      'sushi_combo': 'Combo Sushi',
      'sushi_desc': 'Plateau de sushis frais assortis',

      // Address type names (selector + type picker)
      'apartment_address': 'Appartement',
      'address_type_home': 'Maison',
      'address_type_work': 'Bureau',
      'address_type_apartment': 'Appartement',
      'address_type_other': 'Autre',
      'home_type_subtitle': 'Votre adresse personnelle',
      'work_type_subtitle': 'Votre lieu de travail',
      'apartment_type_subtitle': 'Résidence ou immeuble',
      'other_type_subtitle': 'Toute autre adresse',
      'choose_address_type': 'Choisissez le type de votre adresse',

      // Location / Delivery flow
      'session_expired': 'Session expirée. Veuillez vous reconnecter.',
      'where_to_deliver': 'Où devons-nous livrer ?',
      'choose_on_map': 'Choisir sur la carte',
      'move_pin_to_adjust': 'Déplacez le pin pour ajuster la position',
      'continue_btn': 'Continuer',
      'what_type_of_place': "De quel genre d'endroit s'agit-il ?",
      'address_selected_for_delivery': 'sélectionnée comme adresse de livraison',

      // Addresses Screen
      'my_addresses': 'Mes adresses',
      'add': 'Ajouter',
      'load_addresses_error': 'Impossible de charger les adresses',
      'retry': 'Réessayer',
      'no_address_hint': 'Appuyez sur « Ajouter » pour créer\nvotre première adresse de livraison.',
      'delete_address': 'Supprimer l\'adresse',
      'delete_address_confirm': 'Supprimer cette adresse ? Cette action est irréversible.',
      'delete': 'Supprimer',
      'default_label': 'Défaut',

      // Address Details Screen
      'home_screen_title': 'Adresse Maison',
      'work_screen_title': 'Adresse Bureau',
      'apartment_screen_title': 'Adresse Appartement',
      'other_screen_title': 'Autre adresse',
      'address_gps_section': 'Adresse (détectée par GPS)',
      'address_not_available': 'Adresse non disponible',
      'residence_name': 'Nom de résidence / immeuble',
      'residence_hint': 'Ex: Résidence Les Jardins',
      'floor_section': 'Étage',
      'floor_hint': 'Ex: 3',
      'apartment_number': 'N° Appartement',
      'apartment_hint': 'Ex: A12',
      'extra_info': 'Informations supplémentaires (optionnel)',
      'extra_info_hint': 'Codes d\'accès, sonnette, repère…',
      'address_label_section': 'Étiquette de l\'adresse',
      'label_already_used_badge': 'Étiquette déjà utilisée',
      'label_required': 'Le label est obligatoire pour ce type.',
      'field_required': 'Ce champ est obligatoire.',
      'delete_blocked_title': 'Suppression impossible',
      'delete_blocked_content': 'Cette adresse est actuellement votre adresse de livraison active. Veuillez d\'abord choisir une autre adresse de livraison avant de la supprimer.',
      'understood': 'Compris',
      'address_deleted': 'Adresse supprimée.',
      'address_delete_error': 'Impossible de supprimer l\'adresse. Réessayez.',
      'changes_saved': 'Modifications enregistrées avec succès !',
      'address_added': 'Adresse ajoutée à votre liste !',
      'label_already_used_error': 'Cette étiquette est déjà utilisée par une autre adresse. Choisissez un nom différent ci-dessous \u2193',
      'account_not_found_error': 'Compte introuvable. Veuillez vous reconnecter et réessayer.',
      'invalid_fields_error': 'Certains champs sont invalides. Vérifiez les informations saisies.',
      'invalid_gps_error': 'Les coordonnées GPS sont invalides. Retournez à la carte et sélectionnez à nouveau.',
      'personalized': 'Personnalisé',
      'custom_label_other_hint': 'Ex: Chez grand-mère',

      // Profile Screen
      'use_current_location': 'Utiliser la position actuelle',
      'premium_member': 'MEMBRE PREMIUM',
      'live_badge': 'EN DIRECT',
    },
    'ar': {
      'app_name': 'سبيد لاين',
      'welcome': 'مرحبا',
      'login': 'تسجيل الدخول',
      'log_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'email_address': 'عنوان البريد الإلكتروني',
      'email_hint': 'بريدك@example.com',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'home': 'الرئيسية',
      'orders': 'الطلبات',
      'profile': 'الملف الشخصي',
      'search_restaurants': 'ابحث عن المطاعم...',
      'cart': 'السلة',
      'checkout': 'الدفع',
      'order_placed': 'تم تقديم الطلب بنجاح',
      'track_order': 'تتبع الطلب',
      
      // Auth screens
      'sign_in': 'تسجيل الدخول',
      'first_name': 'الاسم الأول',
      'first_name_hint': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'last_name_hint': 'اسم العائلة',
      'phone_number': 'رقم الهاتف',
      'phone_hint': '+216 22 345 678',
      'or_continue_with': 'أو المتابعة مع',
      'having_trouble': 'تواجه مشكلة؟ ',
      'contact_support': 'اتصل بالدعم',
      
      // Validation messages
      'please_enter_email': 'يرجى إدخال بريدك الإلكتروني',
      'invalid_email': 'بريد إلكتروني غير صالح',
      'please_enter_password': 'يرجى إدخال كلمة المرور',
      'password_min_length': 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
      'please_enter_first_name': 'يرجى إدخال اسمك الأول',
      'please_enter_last_name': 'يرجى إدخال اسم العائلة',
      'please_enter_valid_email': 'يرجى إدخال بريد إلكتروني صالح',
      'please_enter_phone': 'يرجى إدخال رقم هاتفك',
      'phone_min_length': 'يجب أن يحتوي رقم الهاتف على 8 أرقام',
      
      // Forgot Password
      'forgot_password_title': 'نسيت كلمة المرور؟',
      'forgot_password_desc': 'لا تقلق! هذا يحدث. يرجى إدخال عنوان البريد الإلكتروني المرتبط بحسابك.',
      'send_code': 'إرسال الرمز',
      'remember_password': 'تذكرت كلمة المرور؟ ',
      
      // Verify OTP
      'verify_code': 'تحقق من الرمز',
      'verify_code_desc': 'يرجى إدخال الرمز الذي أرسلناه للتو إلى',
      'didnt_receive_code': 'لم تستلم الرمز؟ ',
      'resend': 'إعادة إرسال',
      'please_enter_6_digit_code': 'يرجى إدخال الرمز المكون من 6 أرقام',
      'code_resent_success': 'تم إعادة إرسال الرمز بنجاح',
      'verify_identity': 'التحقق من هويتك',
      'otp_sent_to': 'لقد أرسلنا رمز التحقق إلى',
      'code_expired': 'انتهت صلاحية الرمز',
      'code_expired_message': 'انتهت صلاحية رمز OTP الخاص بك. يرجى طلب رمز جديد.',
      'back': 'رجوع',
      'resend_code': 'إعادة إرسال',
      'expires_in': 'تنتهي الصلاحية في',
      'verify_and_login': 'التحقق وتسجيل الدخول',
      'enter_6_digit_code': 'يرجى إدخال رمز مكون من 6 أرقام',
      'invalid_or_expired_code': 'رمز غير صالح أو منتهي الصلاحية',
      'login_success': '✓ تم تسجيل الدخول بنجاح!',
      'resend_login_otp_message': 'لإعادة إرسال الرمز، يرجى تسجيل الدخول مرة أخرى',
      'wait': 'انتظر',
      'seconds': 'ثانية',
      'sec': 'ث',
      
      // Snackbar messages
      'login_failed': 'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد الخاصة بك.',
      'otp_verification_failed': 'فشل التحقق من OTP. يرجى المحاولة مرة أخرى.',
      'otp_verification_success': 'تم التحقق من OTP بنجاح!',
      'password_reset_failed': 'فشلت إعادة تعيين كلمة المرور. يرجى المحاولة مرة أخرى.',
      'password_reset_complete': 'تمت إعادة تعيين كلمة المرور الخاصة بك بنجاح!',
      'email_not_found': 'البريد الإلكتروني غير موجود. يرجى التحقق والمحاولة مرة أخرى.',
      'invalid_credentials': 'بريد إلكتروني أو كلمة مرور غير صالحة.',
      'generic_error': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      'please_wait': 'يرجى الانتظار...',
      'otp_sent': 'تم إرسال OTP بنجاح إلى بريدك الإلكتروني.',
      'stay_connected': 'ابق متصلاً',
      
      // Accueil Screen
      'welcome_speedline': 'مرحبا بك في سبيد لاين!',
      'welcome_message': 'أنت الآن متصل بحسابك.\nشاشة الرئيسية الكاملة قادمة قريباً!',
      'welcome_user': 'مرحبا',
      
      // Settings Screen
      'settings': 'الإعدادات',
      'account': 'الحساب',
      'edit_profile': 'تعديل الملف الشخصي',
      'manage_preferences': 'إدارة معلومات ملفك الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'update_security_credentials': 'تحديث بيانات الأمان الخاصة بك',
      'app_preferences': 'التفضيلات',
      'language': 'اللغة',
      'choose_app_language': 'اختر لغة التطبيق',
      'dark_mode': 'الوضع الداكن',
      'enable_dark_theme': 'تفعيل المظهر الداكن',
      'dark_mode_enabled': 'تم تفعيل الوضع الداكن',
      'light_mode_enabled': 'تم تفعيل الوضع المضيء',
      'notifications': 'الإشعارات',
      'push_notifications': 'إشعارات الدفع',
      'receive_order_updates': 'تلقي تحديثات الطلبات والعروض',
      'email_notifications': 'إشعارات البريد الإلكتروني',
      'receive_news_offers': 'تلقي الأخبار والعروض الخاصة',
      'support': 'الدعم',
      'help_center': 'مركز المساعدة',
      'faq_support_articles': 'الأسئلة الشائعة ومقالات الدعم',
      'contact_us': 'اتصل بنا',
      'get_in_touch': 'تواصل مع فريقنا',
      'terms_conditions': 'الشروط والأحكام',
      'legal_information': 'المعلومات القانونية والسياسات',
      'about': 'حول',
      'app_version': 'إصدار التطبيق',
      'logout': 'تسجيل الخروج',
      'are_you_sure_logout': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      
      // Enable Location Screen
      'enable_location': 'تفعيل خدمات الموقع',
      'location_permission_title': 'ما هو موقعك؟',
      'location_permission_desc': 'نحتاج إلى معرفة موقعك لإظهار المطاعم القريبة وتقديم تقديرات توصيل دقيقة.',
      'accurate_delivery': 'توفير تقديرات توصيل دقيقة',
      'allow_location_access': 'السماح بالوصول إلى الموقع',
      'enter_address_manually': 'إدخال العنوان يدوياً',
      'skip_for_now': 'تخطي في الوقت الحالي',
      'location_services_disabled': 'خدمات الموقع معطلة. يرجى تفعيلها في الإعدادات.',
      'location_permission_denied': 'تم رفض إذن الموقع. يرجى السماح بالوصول للمتابعة.',
      'location_permanently_denied': 'تم رفض أذونات الموقع بشكل دائم.',
      'open_settings_for_location': 'يرجى فتح إعدادات التطبيق للسماح بخدمة الموقع.',
      'open_settings': 'فتح الإعدادات',
      'location_timeout': 'انتهت مهلة طلب الموقع. يرجى المحاولة مرة أخرى.',
      'location_error': 'فشل في الحصول على الموقع',
      'detecting_location': 'جاري الكشف...',
      'privacy_location_note': 'موقعك مشفر ولن يتم مشاركته أبداً.',
      'enter_your_address': 'أدخل عنوانك',
      'search_address': 'ابحث عن عنوان',
      'address_search_hint': 'مثال: شارع حيدي شاكر، صفاقس',
      'confirm_address': 'تأكيد العنوان',
      'retry_gps': 'إعادة محاولة GPS',
      'manual_address_entry': 'إدخال العنوان يدوياً',
      'manual_address_coming_soon': 'شاشة إدخال العنوان يدوياً قادمة قريباً!',
      'ok': 'حسناً',

      // Confirm Location Screen
      'confirm_your_location': 'تأكيد موقعك',
      'delivery_address': 'عنوان التوصيل',
      'done': 'تم',
      'edit': 'تعديل',
      'enter_address_hint': 'أدخل عنوانك الكامل...',
      'detecting_address': 'جاري الكشف...',
      'no_address_found': 'لم يتم العثور على عنوان.',
      'tap_map_to_adjust': 'اضغط على الخريطة لضبط موضع الدبوس.',
      'confirm_this_location': 'تأكيد هذا الموقع',
      'current_location_label': 'الموقع الحالي',
      'missing_address_data': 'بيانات العنوان مفقودة',
      'default_location': 'صفاقس، تونس',
      'special_for_you': 'خاص لك',
      'stores': 'متاجر',
      'free_delivery_first_order': 'توصيل مجاني لطلبك الأول',
      'order_and_enjoy': 'اطلب واستمتع!',
      
      // Edit Profile Screen
      'save_changes': 'حفظ التغييرات',
      'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح!',
      'profile_update_error': 'فشل تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
      'choose_photo_source': 'اختر مصدر الصورة',
      'take_photo': 'التقاط صورة',
      'choose_from_gallery': 'اختر من المعرض',
      'remove_photo': 'حذف الصورة',
      'uploading': 'جاري الرفع...',
      
      // Profile Screen
      'my_profile': 'ملفي الشخصي',
      'delivery_addresses': 'عناوين التوصيل',
      'manage_addresses': 'إدارة عناوينك',
      'add_new_address': 'إضافة عنوان جديد',
      'no_address_saved': 'لم يتم حفظ أي عنوان بعد',
      'work_address': 'العمل',
      'other_address': 'أخرى',
      'address_type_label': 'نوع العنوان',
      'my_location_btn': 'موقعي',
      'getting_location': 'جارٍ تحديد الموقع...',
      'custom_label_hint': 'مثال: الأهل، الصالة الرياضية...',
      'payment_methods': 'طرق الدفع',
      'manage_payment': 'إدارة طرق الدفع الخاصة بك',
      'add_payment_method': 'إضافة طريقة دفع',
      'order_history': 'سجل الطلبات',
      'view_all_orders': 'عرض جميع طلباتك السابقة',
      'delivered': 'تم التوصيل',
      'reorder': 'إعادة الطلب',
      'view_details': 'عرض التفاصيل',
      'manage_all': 'إدارة الكل',
      'manage': 'إدارة',
      'view_all': 'عرض الكل',
      
      // Search Screen
      'search': 'بحث',
      'coming_soon': 'قريباً...',
      
      // Orders Screen
      'my_orders': 'طلباتي',
      
      // Main Navigation
      'explore': 'استكشف',
      
      // Reset Password
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_desc': 'يرجى إدخال كلمة المرور الجديدة. تأكد من أنها تحتوي على 6 أحرف على الأقل.',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'please_enter_password_field': 'يرجى إدخال كلمة مرور',
      'minimum_6_chars': 'الحد الأدنى 6 أحرف',
      'please_confirm_password': 'يرجى تأكيد كلمة المرور',
      'passwords_dont_match': 'كلمات المرور غير متطابقة',
      'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح!',
      
      // Change Password
      'change_password_title': 'تغيير كلمة المرور',
      'change_password_desc': 'لتغيير كلمة المرور، سنرسل رمز التحقق إلى عنوان بريدك الإلكتروني.',
      'continue_to_verify': 'متابعة',
      'secure_account': 'حافظ على أمان حسابك عن طريق تغيير كلمة المرور بانتظام.',
      
      // Social login in development
      'google_signin_dev': 'تسجيل الدخول عبر Google - قيد التطوير',
      'facebook_signin_dev': 'تسجيل الدخول عبر Facebook - قيد التطوير',
      'register_success': 'تم التسجيل بنجاح! الرجاء تسجيل الدخول باستخدام بيانات الاعتماد الخاصة بك.',
      
      // Home/Onboarding screen
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ',
      'terms_prefix': 'بالمتابعة، فإنك توافق على ',
      'terms': 'الشروط',
      'privacy_policy': 'سياسة الخصوصية',
      
      // Onboarding pages
      'onboarding_page1_title': 'التوصيل مع',
      'onboarding_page1_highlight': 'السرعة والدقة',
      'onboarding_page1_desc': 'إدارة أسطولك في الوقت الفعلي. أسرع طريقة للانتقال من أ إلى ب تبدأ هنا.',
      'onboarding_page2_title': 'تتبع',
      'onboarding_page2_highlight': 'طلبك مباشرة',
      'onboarding_page2_desc': 'التتبع في الوقت الفعلي يبقيك على اطلاع في كل خطوة. لن تفوت أي توصيل.',
      'onboarding_page3_title': 'خدمة سريعة',
      'onboarding_page3_highlight': 'وموثوقة',
      'onboarding_page3_desc': 'استمتع بتوصيل سريع للغاية مع شبكتنا الموثوقة من السعاة المحترفين.',
      
      // Explore Screen
      'restaurants': 'المطاعم',
      'courses': 'الدورات',
      'service_courier': 'خدمة المندوب',
      'select_location': 'اختر الموقع',
      'for_you': 'هذا من أجلك',
      'promotions': 'العروض الترويجية',
      'magasins_aziza': 'متاجر عزيزة',
      'free_delivery_title': 'توصيل مجاني',
      'order_now': 'اطلب الآن، نحن نعاملك!',
      
      // Explore Screen
      'deliver_to': 'التوصيل إلى',
      'current_location': 'الموقع الحالي',
      'welcome_back': 'مرحبا بعودتك!',
      'what_would_you_like': 'ماذا تريد أن تطلب اليوم؟',
      'browse_categories': 'تصفح الفئات',
      'groceries': 'البقالة',
      'special_offer': 'عرض خاص',
      'exclusive_deals': 'عروض وخصومات حصرية',
      'save_up_to': 'وفر حتى 50٪ على العناصر المختارة',
      'explore_now': 'استكشف الآن',
      'free_delivery_desc': 'على طلبك الأول بقيمة 15 دولارًا أو أكثر',
      'popular_now': 'الأكثر شعبية الآن',
      'see_all': 'عرض الكل',
      'pizza_margherita': 'بيتزا مارغريتا',
      'pizza_desc': 'موزاريلا طازجة، صلصة طماطم',
      'sushi_combo': 'سوشي كومبو',
      'sushi_desc': 'طبق سوشي طازج متنوع',

      // Address type names (selector + type picker)
      'apartment_address': 'شقة',
      'address_type_home': 'منزل',
      'address_type_work': 'مكتب',
      'address_type_apartment': 'شقة',
      'address_type_other': 'أخرى',
      'home_type_subtitle': 'عنوانك الشخصي',
      'work_type_subtitle': 'مكان عملك',
      'apartment_type_subtitle': 'مقر إقامة أو مبنى',
      'other_type_subtitle': 'أي عنوان آخر',
      'choose_address_type': 'اختر نوع عنوانك',

      // Location / Delivery flow
      'session_expired': 'انتهت الجلسة. يرجى تسجيل الدخول مجدداً.',
      'where_to_deliver': 'أين نوصل؟',
      'choose_on_map': 'اختر على الخريطة',
      'move_pin_to_adjust': 'حرّك الدبوس لضبط الموقع',
      'continue_btn': 'متابعة',
      'what_type_of_place': 'ما نوع هذا المكان؟',
      'address_selected_for_delivery': 'تم اختيارها كعنوان توصيل',

      // Addresses Screen
      'my_addresses': 'عناويني',
      'add': 'إضافة',
      'load_addresses_error': 'تعذر تحميل العناوين',
      'retry': 'إعادة المحاولة',
      'no_address_hint': 'اضغط « إضافة » لإنشاء\nأول عنوان توصيل.',
      'delete_address': 'حذف العنوان',
      'delete_address_confirm': 'هل تريد حذف هذا العنوان؟ لا يمكن التراجع عن هذا الإجراء.',
      'delete': 'حذف',
      'default_label': 'افتراضي',

      // Address Details Screen
      'home_screen_title': 'عنوان المنزل',
      'work_screen_title': 'عنوان العمل',
      'apartment_screen_title': 'عنوان الشقة',
      'other_screen_title': 'عنوان آخر',
      'address_gps_section': 'العنوان (مكتشف عبر GPS)',
      'address_not_available': 'العنوان غير متاح',
      'residence_name': 'اسم المبنى / المقر',
      'residence_hint': 'مثال: إقامة البساتين',
      'floor_section': 'الطابق',
      'floor_hint': 'مثال: 3',
      'apartment_number': 'رقم الشقة',
      'apartment_hint': 'مثال: A12',
      'extra_info': 'معلومات إضافية (اختياري)',
      'extra_info_hint': 'رموز الدخول، الجرس، المعلم...',
      'address_label_section': 'تسمية العنوان',
      'label_already_used_badge': 'التسمية مستخدمة مسبقاً',
      'label_required': 'التسمية مطلوبة لهذا النوع.',
      'field_required': 'هذا الحقل إلزامي.',
      'delete_blocked_title': 'لا يمكن الحذف',
      'delete_blocked_content': 'هذا هو عنوان التوصيل النشط حالياً. يرجى اختيار عنوان آخر قبل حذفه.',
      'understood': 'حسناً',
      'address_deleted': 'تم حذف العنوان.',
      'address_delete_error': 'تعذر حذف العنوان. يرجى المحاولة مجدداً.',
      'changes_saved': 'تم حفظ التغييرات بنجاح!',
      'address_added': 'تمت إضافة العنوان إلى قائمتك!',
      'label_already_used_error': 'هذه التسمية مستخدمة من قبل عنوان آخر. اختر اسماً مختلفاً أدناه \u2193',
      'account_not_found_error': 'الحساب غير موجود. يرجى تسجيل الدخول مجدداً.',
      'invalid_fields_error': 'بعض الحقول غير صالحة. يرجى التحقق من المعلومات المدخلة.',
      'invalid_gps_error': 'إحداثيات GPS غير صالحة. عد إلى الخريطة وحدد الموقع مجدداً.',
      'personalized': 'مخصص',
      'custom_label_other_hint': 'مثال: بيت الجدة',

      // Profile Screen
      'use_current_location': 'استخدام الموقع الحالي',
      'premium_member': 'عضو مميز',
      'live_badge': 'مباشر',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
